-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------]]
TEAM_CITIZEN = DarkRP.createJob("Citizen", {
    color = Color(155, 255, 155, 255),
    model = {
        "models/kayf/humans/group02/male_09.mdl",
        "models/kayf/humans/group02/male_08.mdl",
        "models/kayf/humans/group02/male_03.mdl",
        "models/kayf/humans/group01/male_07.mdl",
        "models/kayf/humans/group01/male_05.mdl",
        "models/kayf/humans/group01/male_01.mdl",
		"models/obese_male.mdl",
		"models/kayf/humans/group02/female_07.mdl",
        "models/kayf/humans/group02/female_06.mdl",
        "mmodels/kayf/humans/group02/female_03.mdl",
        "models/kayf/humans/group02/female_02.mdl",
        "models/kayf/humans/group01/female_03.mdl",
        "models/kayf/humans/group01/female_02.mdl",
    },
    description = [[Citizens are normal people, nothing special and make up the majority of the server.

-Income and Salary-
   $50/10min
  
-Special Commands-
   None
   
-Abilities-
   None
  
]],
    weapons = {"cw_p99"},
    command = "citizen",
    max = 0,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Civilians",
})

TEAM_POLICE = DarkRP.createJob("Law Enforcement", {
    color = Color(0, 140, 255, 255),
    model = {
        "models/kerry/player/police_usa/male_04.mdl",
        "models/kerry/player/police_usa/male_05.mdl",
        "models/kerry/player/police_usa/male_06.mdl",
		"models/kerry/player/police_usa/male_03.mdl",
        "models/kerry/player/police_usa/male_01.mdl",
    },
    description = [[Law enforcement have the authority to uphold the law, whether that be by issuing fines, arresting criminals, or killing armed psychos.

-Income and Salary-
   $200/10min
   Cash reward for destroying printers
   
-Special Commands-
   /wanted <PLAYER> - Sets that player as Wanted (needed to arrest)
   /warrant <PLAYER> - Requests a warrant to search player's property
   /agenda - Sets shared police agenda
   /addagenda - Adds line to shared police agenda
   
-Abilities-
   Can issue tickets
   Can make arrests
   Can search people
   
]],
    weapons = {"arrest_stick", "unarrest_stick", "cw_nen_glock17", "stunstick", "door_ram", "weaponchecker"},
    command = "cp",
    max = 6,
    salary = 250,
    admin = 0,
    vote = true,
    hasLicense = true,
    ammo = {
        ["pistol"] = 60,
    },
    category = "Government",
})

TEAM_SEC = DarkRP.createJob("Security", {
    color = Color(0, 140, 255, 255),
    model = {
        "models/player/bankguard/male_01.mdl",
        "models/player/bankguard/male_04.mdl",
        "models/player/bankguard/male_08.mdl",
        "models/player/bankguard/male_03.mdl",
    },
    description = [[Security guards are hired by individuals to protect businesses or VIPs. Depending on the situation, you may need to call police for assistance.

-Income and Salary-
   $150/10min
   Any profits from guard assignments
  
-Special Commands-
   None
   
-Abilities-
   Can search people
  
]],
    weapons = {"cw_nen_glock17", "stunstick", "weaponchecker"},
    command = "sec",
    max = 3,
    salary = 150,
    admin = 0,
    vote = false,
    hasLicense = true,
    ammo = {
        ["pistol"] = 60,
    },
    category = "Civilians",
})

TEAM_GANG = DarkRP.createJob("Criminal", {
    color = Color(164,0,235, 255),
    model = {
        "models/kayf/humans/group01/male_01.mdl",
        "models/kayf/humans/group01/male_02.mdl",
		"models/kayf/humans/group01/male_05.mdl",
        "models/kayf/humans/group02/female_01.mdl",
        "models/kayf/humans/group02/female_03.mdl",
        "models/deepalley/alley_thug.mdl",
		"models/Player/betaconscript.mdl",
        "models/ms13/slow_1.mdl",
		"models/ms13/slow_2.mdl",
		"models/ms13/slow_3.mdl",
		"models/obese_male.mdl",
		"models/player/phillStyle.mdl",
        },
    description = [[You are a career criminal. You often choose the less-than-legal route to get rich. In between running from the cops you make a living by robbing those you deem weaker than you.

-Income and Salary-
   $50/10min
   Any profits from criminal activity
  
-Special Commands-
   None
   
-Abilities-
   None
  
]],
    weapons = {lockpick},
    command = "gangster",
    max = 4,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Law-Breakers",
})

TEAM_KILL = DarkRP.createJob("Serial Killer", {
    color = Color(155,25,25, 255),
    model = {
        "models/kayf/humans/group01/male_01.mdl",
        "models/kayf/humans/group01/male_02.mdl",
		"models/kayf/humans/group01/male_05.mdl",
        "models/kayf/humans/group02/female_01.mdl",
        "models/kayf/humans/group02/female_03.mdl",
        "models/deepalley/alley_thug.mdl",
        "models/ms13/slow_1.mdl",
		"models/ms13/slow_2.mdl",
		"models/ms13/slow_3.mdl",
		"models/obese_male.mdl",
		"models/player/phillStyle.mdl",
		"models/Player/betaconscript.mdl",
        },
    description = [[A serial killer finds pleasure in ending the lives of random strangers. It's almost an artform.

-Income and Salary-
   $150/10min
  
-Special Commands-
   None
   
-Abilities-
   Can kill random people
  
]],
    weapons = {weapon_lo_machete},
    command = "killer",
    max = 1,
    salary = 150,
    admin = 0,
    vote = true,
    hasLicense = false,
    category = "Law-Breakers",
})

TEAM_MOB = DarkRP.createJob("Kingpin", {
    color = Color(172,0,255, 255),
    model = {
        "models/kayf/humans/group01/male_08.mdl",
        "models/fearless/mayor1.mdl",
        "models/fearless/mayor2.mdl",
        "models/ms13/slow_3.mdl",
		"models/kayf/humans/group02/male_04.mdl",
		"models/Player/betaconscript.mdl",
    },
    description = [[The kingpin is the boss of the criminal underworld. Employ an army of underlings to do your dirty work and run your very own crime empire. Keep yourself protected at all times, as some people may be interested in taking you out.

-Income and Salary-
   $600/10min
   Any profits from rackets
  
-Special Commands-
   /agenda - Sets gang agenda
   /addagenda - Adds line to gang agenda
   
-Abilities-
   You have a forged gun license
   Break people out of jail
   People may want to work for you
  
]],
    weapons = {"lockpick","cw_shorty", "unarrest_stick"},
    command = "mobboss",
    max = 1,
    salary = 600,
    admin = 0,
    vote = false,
    hasLicense = true,
    category = "Law-Breakers",
	ammo = {
        ["12 Gauge Rounds"] = 60,
    },
	NeedToChangeFrom = TEAM_GANG,
})

TEAM_GUN = DarkRP.createJob("Arms Dealer", {
    color = Color(255, 255, 0, 255),
    model = {
        "models/kayf/humans/group02/male_09.mdl",
        "models/kayf/humans/group02/male_08.mdl",
        "models/kayf/humans/group02/male_03.mdl",
        "models/kayf/humans/group01/male_07.mdl",
        "models/kayf/humans/group01/male_05.mdl",
        "models/kayf/humans/group01/male_01.mdl",
		"models/Player/betaconscript.mdl",
		"models/kayf/humans/group02/female_07.mdl",
        "models/kayf/humans/group02/female_06.mdl",
        "mmodels/kayf/humans/group02/female_03.mdl",
        "models/kayf/humans/group02/female_02.mdl",
        "models/kayf/humans/group01/female_03.mdl",
        "models/kayf/humans/group01/female_02.mdl",
    },
    description = [[Arms dealers sell weapons to those who have the cash to buy. With such a popular product, you'll have no trouble finding business opportunities.

-Income and Salary-
   $100/10min
   Any profits from sales
  
-Special Commands-
   None
   
-Abilities-
   Can sell weapons
   Can sell ammunition
  
]],
    weapons = {},
    command = "gundealer",
    max = 2,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = true,
    category = "Vendors",
})

TEAM_BLACKMARKET = DarkRP.createJob("Black Market", {
    color = Color(55, 55, 55, 255),
    model = {
        "models/kayf/humans/group01/male_01.mdl",
        "models/kayf/humans/group01/male_02.mdl",
		"models/kayf/humans/group01/male_05.mdl",
        "models/kayf/humans/group02/female_01.mdl",
        "models/kayf/humans/group02/female_03.mdl",
        "models/deepalley/alley_thug.mdl",
		"models/Player/betaconscript.mdl",
        "models/ms13/slow_1.mdl",
		"models/ms13/slow_2.mdl",
		"models/ms13/slow_3.mdl",
		"models/obese_male.mdl",
		"models/player/phillStyle.mdl",
        },
    description = [[Black Market dealers sell merchandise that is highly illegal. You'll no doubt make good money with the right people.

-Income and Salary-
   $50/10min
   Any profits from sales
  
-Special Commands-
   None
   
-Abilities-
   Can sell explosives
   Can sell printers
   Can sell assault weapons
  
]],
    weapons = {},
    command = "blackmarket",
    max = 1,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Law-Breakers",
})

TEAM_HITMAN = DarkRP.createJob("Hitman", {
    color = Color(155, 25, 25, 255),
    model = {
        "models/kayf/humans/group01/male_01.mdl",
        "models/kayf/humans/group01/male_02.mdl",
		"models/kayf/humans/group01/male_05.mdl",
        "models/kayf/humans/group02/female_01.mdl",
        "models/kayf/humans/group02/female_03.mdl",
        "models/deepalley/alley_thug.mdl",
		"models/Player/betaconscript.mdl",
        "models/ms13/slow_1.mdl",
		"models/ms13/slow_2.mdl",
		"models/ms13/slow_3.mdl",
		"models/obese_male.mdl",
		"models/player/phillStyle.mdl",
        },
    description = [[Hitmen are hired murderers, their trade is taking lives for the right price.

-Income and Salary-
   $75/10min
   Any profits from hits
  
-Special Commands-
   None
   
-Abilities-
   Gets access to assassination contracts
  
]],
    weapons = {},
    command = "hitman",
    max = 1,
    salary = 75,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Law-Breakers",
})

TEAM_DRUG = DarkRP.createJob("Drug Dealer", {
    color = Color(55, 55, 55, 255),
    model = {
        "models/kayf/humans/group01/male_01.mdl",
        "models/kayf/humans/group01/male_02.mdl",
		"models/jessev92/player/l4d/m9-hunter.mdl",
		"models/kayf/humans/group01/male_05.mdl",
        "models/kayf/humans/group02/female_01.mdl",
        "models/kayf/humans/group02/female_03.mdl",
        "models/deepalley/alley_thug.mdl",
		"models/Player/betaconscript.mdl",
        "models/ms13/slow_1.mdl",
		"models/ms13/slow_2.mdl",
		"models/ms13/slow_3.mdl",
		"models/obese_male.mdl",
		"models/player/phillStyle.mdl",
        },
    description = [[Drug dealers peddle the good stuff.

-Income and Salary-
   $50/10min
   Any profits from sales
  
-Special Commands-
   None
   
-Abilities-
   Can sell drugs
  
]],
    weapons = {},
    command = "drugdealer",
    max = 4,
    salary = 50,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Law-Breakers",
})

TEAM_MEDIC = DarkRP.createJob("Rescue", {
    color = Color(255, 114, 0, 255),
    model = {
        "models/player/kerry/medic/medic_01.mdl",
        "models/player/kerry/medic/medic_03.mdl",
        "models/player/kerry/medic/medic_06.mdl",
        "models/player/kerry/medic/medic_04_f.mdl",
        "models/player/kerry/medic/medic_05_f.mdl",
        "models/player/kerry/medic/medic_03_f.mdl",
    },
    description = [[Rescue is there to help people. You'll find work by healing people and putting out fires, some of which may be arson.

-Income and Salary-
   $200/10min
   Any profits from services
  
-Special Commands-
   None
   
-Abilities-
   Can heal people
   Can put out fires
   Can sell morphine syringes
  
]],
    weapons = {"med_kit","weapon_extinguisher"},
    command = "medic",
    max = 3,
    salary = 200,
    admin = 0,
    vote = false,
    hasLicense = false,
    medic = true,
    category = "Government",
})

TEAM_CHIEF = DarkRP.createJob("Federal Agent", {
    color = Color(0, 36, 195, 255),
     model = {
        "models/fbi_pack/fbi_05.mdl",
        "models/fbi_pack/fbi_06.mdl",
        "models/fbi_pack/fbi_01.mdl",
        "models/fbi_pack/fbi_03.mdl",
    },
    description = [[Federal Agents are mainly in charge of high-risk criminals and drug crime.

-Income and Salary-
   $400/10min
  
-Special Commands-
   /wanted <PLAYER> - Sets that player as Wanted (needed to arrest)
   /warrant <PLAYER> - Requests a warrant to search player's property
   /agenda - Sets shared police agenda
   /addagenda - Adds line to shared police agenda
   
-Abilities-
   Can issue tickets
   Can make arrests
   Can search people
  
]],
    weapons = {"arrest_stick", "unarrest_stick", "cw_mp7_official", "stunstick", "door_ram", "weaponchecker"},
    command = "chief",
    max = 2,
    salary = 400,
    admin = 0,
    vote = true,
    hasLicense = true,
    chief = true,
    NeedToChangeFrom = TEAM_POLICE,
    ammo = {
        ["pistol"] = 60,
    },
    category = "Government",
})

TEAM_MAYOR = DarkRP.createJob("Mayor", {
    color = Color(0, 255, 255, 255),
   model = {
        "models/fearless/mayor1.mdl",
        "models/fearless/mayor2.mdl",
    },
    description = [[You are the elected official of the city. Being such an important person you may find yourself with a price on your head. Stay protected at all times, as you will lose your job upon death.

-Income and Salary-
   $800/10min
  
-Special Commands-
   /wanted <PLAYER> - Sets that player as Wanted (needed to arrest)
   /warrant <PLAYER> - Requests a warrant to search player's property
   /agenda - Sets shared police agenda
   /addagenda - Adds line to shared police agenda
   
-Abilities-
   Can edit laws
   Can issue licenses
   Can accept or veto warrants
  
]],
    weapons = {},
    command = "mayor",
    max = 1,
    salary = 800,
    admin = 0,
    vote = true,
    hasLicense = true,
    mayor = true,
    category = "Government",
})

TEAM_HOBO = DarkRP.createJob("Hobo", {
    color = Color(202,179,31,255),
   model = {       
        "models/player/corpse1.mdl",
		"models/player/eli.mdl",
		"models/Player/betaconscript.mdl",
        "models/jessev92/player/l4d/m9-hunter.mdl",
	},
    description = [[Hobos are the lowest members of society. You have no regular income and no safe housing, taking it day by day.

-Income and Salary-
   $0/10min
  
-Special Commands-
   None
   
-Abilities-
   Can sell garbage
]],
    weapons = {"weapon_angryhobo"},
    command = "hobo",
    max = 5,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    hobo = true,
    category = "Civilians",
})

TEAM_STAFF = DarkRP.createJob("Staff-On-Duty", {
    color = Color(0,0,0,255),
    model = "models/player/jesus/jesus.mdl",
    description = [[For staff members to use when lots of players are on.
Cannot participate in roleplay.]],
    weapons = {"weapon_extinguisher_infinite"},
    command = "sod",
    max = 3,
    salary = 0,
    admin = 1,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Government",
})


if not DarkRP.disabledDefaults["modules"]["hungermod"] then
    TEAM_COOK = DarkRP.createJob("Cook", {
        color = Color(238, 99, 99, 255),
        model = {       
        "models/darkrp/cook/bbq_m.mdl",
        "models/darkrp/cook/bbq_f.mdl",
	},
        description = [[Cooks are responsible for providing food to the local populace.

-Income and Salary-
   $80/10min
   Any profits from sales
  
-Special Commands-
   /buyoven - Purchase a microwave for food
   
-Abilities-
   Purchase food for resale
  
]],
        weapons = {},
        command = "cook",
        max = 2,
        salary = 80,
        admin = 0,
        vote = false,
        hasLicense = false,
        cook = true
		
    })
end


--[[---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------]]
GAMEMODE.DefaultTeam = TEAM_CITIZEN
--[[---------------------------------------------------------------------------
Define which teams belong to civil protection
Civil protection can set warrants, make people wanted and do some other police related things
---------------------------------------------------------------------------]]
GAMEMODE.CivilProtection = {
    [TEAM_POLICE] = true,
    [TEAM_CHIEF] = true,
    [TEAM_MAYOR] = true,

}
--[[---------------------------------------------------------------------------
Jobs that are hitmen (enables the hitman menu)
---------------------------------------------------------------------------]]
